## Masukan library Pandas dan dataset ke dalam variabel data

In [10]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [11]:
data = pd.read_csv("dataset.csv", sep=';')

In [12]:
data.head()

,religion,requestedprincipal,periodcount,gender,education,lengthofemployment,referencegender,monthlygrosssalary,residencestatus,maritalstatus,numberofdependents,employmentstatus,lineofbusiness,refrelationship,appclientage,label
0,1,2000000.0,30,1,1,6.0,1,16886186,1,1,2.0,1,1,1,1,1
1,1,1000000.0,30,2,2,5.0,2,3680000,2,2,1.0,2,19,2,2,1
2,1,3000000.0,10,1,2,1.0,1,4000000,2,2,1.0,2,17,8,3,1
3,1,2000000.0,30,2,2,5.0,2,5000000,2,3,0.0,1,15,2,2,1
4,3,2000000.0,30,1,1,6.0,1,8000000,2,3,0.0,1,23,2,3,1

## Merubah tipe data dari int64 menjadi kategori

In [13]:
data['religion']= data['religion'].astype('category')
data['requestedprincipal']= data['requestedprincipal'].astype('int64')
data['periodcount']= data['periodcount'].astype('category')
data['gender']= data['gender'].astype('category')
data['education']= data['education'].astype('category')
data['lengthofemployment']= data['lengthofemployment'].astype('int64')
data['referencegender']= data['referencegender'].astype('category')
data['monthlygrosssalary']= data['monthlygrosssalary'].astype('category')
data['residencestatus']= data['residencestatus'].astype('category')
data['maritalstatus']= data['maritalstatus'].astype('category')
data['numberofdependents']= data['numberofdependents'].astype('int64')
data['employmentstatus']= data['employmentstatus'].astype('category')
data['lineofbusiness']= data['lineofbusiness'].astype('category')
data['refrelationship']= data['refrelationship'].astype('category')
data['appclientage']= data['appclientage'].astype('category')
data['label']= data['label'].astype('category')

## Melakukan input fitur ke dalam variabel X dan label ke dalam variabel y

In [14]:
X = data.drop('label', axis=1)
y = data['label']

## Melakukan pembagian data train dan data test

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [7]:
print("Total data Train Good Applicant: {}".format(sum(y_train==1)))
print("Total data Train Bad Applicant: {} \n".format(sum(y_train==0)))

Total data Train Good Applicant: 7300
Total data Train Bad Applicant: 1800

In [8]:
print("Total data Train Good Applicant: {}".format(sum(y_test==1)))
print("Total data Train Bad Applicant: {} \n".format(sum(y_test==0)))

Total data Train Good Applicant: 3158
Total data Train Bad Applicant: 742

In [9]:
X_train.shape, X_test.shape

((9100, 15), (3900, 15))

In [10]:
tree = [25, 50, 100, 500, 1000]
mtry = [2, 4, 8]
for x in tree:
    for y in mtry:
        rfc = RandomForestClassifier(bootstrap=True, max_features=y, n_estimators=x,
                                     class_weight=None, criterion='gini',
                                     max_depth=None, max_leaf_nodes=None,
                                     min_impurity_decrease=0.0, min_impurity_split=None,
                                     min_samples_leaf=1, min_samples_split=2,
                                     min_weight_fraction_leaf=0.0, n_jobs=1,
                                     oob_score=True, random_state=1, verbose=0,
                                     warm_start=False)

        print("=== Model Random Forest dengan n_estimators :", x ,"dan mtry :",y,"===")
        rfc = rfc.fit(X_train, y_train)
        rfc_predict=rfc.predict(X_test)
        print("=== Confusion Matrix ===")
        print(confusion_matrix(y_test, rfc_predict))
        print('\n')
        print("Train Accuracy",rfc.score(X_train, y_train))
        print("Test Accuracy",rfc.score(X_test, y_test))
        print("AUC score:",metrics.roc_auc_score(y_test, rfc_predict))
        print("======================================================================")

=== Model Random Forest dengan n_estimators : 25 dan mtry : 2 ===
=== Confusion Matrix ===
[[  64  678]
 [ 118 3040]]


Train Accuracy 0.9950549450549451
Test Accuracy 0.7958974358974359
AUC score: 0.5244439740598045
======================================================================
=== Model Random Forest dengan n_estimators : 25 dan mtry : 4 ===
=== Confusion Matrix ===
[[  72  670]
 [ 128 3030]]


Train Accuracy 0.9953846153846154
Test Accuracy 0.7953846153846154
AUC score: 0.5282515290820046
======================================================================
=== Model Random Forest dengan n_estimators : 25 dan mtry : 8 ===
=== Confusion Matrix ===
[[  91  651]
 [ 180 2978]]


Train Accuracy 0.9949450549450549
Test Accuracy 0.786923076923077
AUC score: 0.5328217046853155
======================================================================
=== Model Random Forest dengan n_estimators : 50 dan mtry : 2 ===
=== Confusion Matrix ===
[[  61  681]
 [ 109 3049]]


Train Accuracy 0.9983516483516484
Test Accuracy 0.7974358974358975
AUC score: 0.5238473632190697
======================================================================
=== Model Random Forest dengan n_estimators : 50 dan mtry : 4 ===
=== Confusion Matrix ===
[[  80  662]
 [ 112 3046]]


Train Accuracy 0.9982417582417582
Test Accuracy 0.8015384615384615
AUC score: 0.536175613553223
======================================================================
=== Model Random Forest dengan n_estimators : 50 dan mtry : 8 ===
=== Confusion Matrix ===
[[  91  651]
 [ 136 3022]]


Train Accuracy 0.9981318681318682
Test Accuracy 0.7982051282051282
AUC score: 0.5397881391375005
======================================================================
=== Model Random Forest dengan n_estimators : 100 dan mtry : 2 ===
=== Confusion Matrix ===
[[  54  688]
 [  90 3068]]


Train Accuracy 0.9986813186813187
Test Accuracy 0.8005128205128205
AUC score: 0.5221386151458923
======================================================================
=== Model Random Forest dengan n_estimators : 100 dan mtry : 4 ===
=== Confusion Matrix ===
[[  68  674]
 [  97 3061]]


Train Accuracy 0.9986813186813187
Test Accuracy 0.8023076923076923
AUC score: 0.5304642810199229
======================================================================
=== Model Random Forest dengan n_estimators : 100 dan mtry : 8 ===
=== Confusion Matrix ===
[[  82  660]
 [ 116 3042]]


Train Accuracy 0.9986813186813187
Test Accuracy 0.801025641025641
AUC score: 0.5368900102251758
======================================================================
=== Model Random Forest dengan n_estimators : 500 dan mtry : 2 ===
=== Confusion Matrix ===
[[  52  690]
 [  76 3082]]


Train Accuracy 0.9986813186813187
Test Accuracy 0.8035897435897436
AUC score: 0.5230074990312542
======================================================================
=== Model Random Forest dengan n_estimators : 500 dan mtry : 4 ===
=== Confusion Matrix ===
[[  63  679]
 [  81 3077]]


Train Accuracy 0.9986813186813187
Test Accuracy 0.8051282051282052
AUC score: 0.5296282576744297
======================================================================
=== Model Random Forest dengan n_estimators : 500 dan mtry : 8 ===
=== Confusion Matrix ===
[[  70  672]
 [  92 3066]]


Train Accuracy 0.9986813186813187
Test Accuracy 0.8041025641025641
AUC score: 0.532603630193459
======================================================================
=== Model Random Forest dengan n_estimators : 1000 dan mtry : 2 ===
=== Confusion Matrix ===
[[  53  689]
 [  75 3083]]


Train Accuracy 0.9986813186813187
Test Accuracy 0.8041025641025641
AUC score: 0.5238396815344251
======================================================================
=== Model Random Forest dengan n_estimators : 1000 dan mtry : 4 ===
=== Confusion Matrix ===
[[  64  678]
 [  82 3076]]


Train Accuracy 0.9986813186813187
Test Accuracy 0.8051282051282052
AUC score: 0.5301437840661375
======================================================================
=== Model Random Forest dengan n_estimators : 1000 dan mtry : 8 ===
=== Confusion Matrix ===
[[  73  669]
 [  90 3068]]


Train Accuracy 0.9986813186813187
Test Accuracy 0.8053846153846154
AUC score: 0.53494184964724
======================================================================

In [13]:
import pandas as pd
data_kasus = pd.read_csv("data_kasus.csv", sep=';')
X_kasus = data_kasus.drop('label', axis=1)
y_kasus = data_kasus['label']

In [14]:
print("Total data kasus Good Applicant: {}".format(sum(y_kasus==1)))
print("Total data kasus Bad Applicant: {} \n".format(sum(y_kasus==0)))

Total data kasus Good Applicant: 32
Total data kasus Bad Applicant: 18

In [15]:
rfc = RandomForestClassifier(bootstrap=True, max_features=8, n_estimators=50,
                                     class_weight=None, criterion='gini',
                                     max_depth=None, max_leaf_nodes=None,
                                     min_impurity_decrease=0.0, min_impurity_split=None,
                                     min_samples_leaf=1, min_samples_split=2,
                                     min_weight_fraction_leaf=0.0, n_jobs=1,
                                     oob_score=True, random_state=1, verbose=0,
                                     warm_start=False)

print("=== Model Random Forest dengan n_estimators :", 8,"dan mtry :",50,"===")
rfc = rfc.fit(X_train, y_train)
rfc_predict=rfc.predict(X_kasus)
from sklearn import metrics
print("Accuracy",rfc.score(X_kasus, y_kasus))

=== Model Random Forest dengan n_estimators : 8 dan mtry : 50 ===
Accuracy 0.62

In [16]:
rfc_predict

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [17]:
rfc_predict = pd.DataFrame (rfc_predict)

In [18]:
asd = pd.concat([rfc_predict, y_kasus],axis=1)

In [19]:
asd

    0  label
0   1      1
1   1      1
2   1      1
3   1      1
4   1      1
5   1      1
6   1      0
7   1      0
8   1      0
9   1      0
10  1      0
11  1      0
12  1      0
13  1      0
14  0      1
15  1      0
16  1      1
17  1      0
18  1      1
19  1      1
20  1      1
21  1      1
22  1      0
23  1      1
24  1      1
25  1      1
26  1      0
27  1      1
28  1      0
29  1      1
30  0      1
31  1      1
32  1      1
33  1      1
34  1      0
35  0      0
36  1      0
37  1      1
38  1      1
39  1      0
40  1      1
41  1      1
42  1      1
43  1      1
44  1      1
45  1      1
46  1      1
47  1      1
48  1      1
49  1      0

In [ ]:
# apply the model to the test set and output score - held back data
rfc.score(X_test, y_test)

In [20]:
# predict on some new data
Xnew = [[1,2000000,30,2,3,6,2,8700000,2,3,0,  1,12,1,3]]
ynew = rfc.predict(Xnew)
yprob = rfc.predict_proba(Xnew)
print("X=%s, Predicted=%s, Probability=%s" % (Xnew[0], ynew[0], yprob[0]))

X=[1, 2000000, 30, 2, 3, 6, 2, 8700000, 2, 3, 0, 1, 12, 1, 3], Predicted=0, Probability=[0.82 0.18]

In [23]:
import pickle
# save the model to disk
filename = 'model-credit.sav'
pickle.dump(rfc, open(filename, 'wb'))

In [ ]:
# some time later...
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict([[1,1000000,30,2,2,6,2,5500000,2,2,3,1,19,2,2]])
probability = loaded_model.predict_proba([[1,1000000,30,2,2,6,2,5500000,2,2,3,1,19,2,2]])
print(result, probability)

In [ ]:
rfc_predict=rfc.predict(X_test)

In [ ]:
print(confusion_matrix(y_test, rfc))